// This file will be auto-generated by Orval from OpenAPI spec
// Placeholder until generation is set up

export interface Product {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  base_price: number;
  compare_at_price: number | null;
  brand: string | null;
  is_published: boolean;
  stock_quantity: number;
  sku: string;
  created_at: string;
  updated_at: string;
}

export interface ProductImage {
  id: string;
  product_id: string;
  storage_path: string;
  display_order: number;
  alt_text: string | null;
  is_primary: boolean;
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  parent_id: string | null;
  display_order: number;
  is_active: boolean;
}

export interface CartItem {
  id: string;
  product_id: string;
  name: string;
  price: number;
  quantity: number;
  image: string;
  variant?: string;
}
